SELECT sum(SALARY), d.name from PERSONS p LEFT OUTER JOIN DEPARTMENTS d ON  d.id = p.DEPARTMENT_ID

  GROUP BY d.NAME;

SELECT * FROM DEPARTMENTS d RIGHT JOIN PERSONS pe LEFT JOIN POSITIONS po
  ON po.ID= pe.POSITION_ID
  ON d.ID = pe.DEPARTMENT_ID;

INSERT INTO PERSONS (ID, FULL_NAME, POSITION_ID, DEPARTMENT_ID, SALARY) VALUES (12,'Ivavon Ivan', 1, NULL , 10000);

CREATE INDEX IDX_PERSON_FULL_NAME on PERSONS ("FULL_NAME")
